version: "3"
services:
 ecos:
  image: ${NOTIFICATIONS_TAG}
  container_name: ecos-notifications
  hostname: ${NOTIFICATIONS_HOST}
  expose:
   - "8013/tcp"
  volumes:
   - "${ECOS_SRC_PATH}/notifications/credentials:/credentials"
  healthcheck:
   test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8013/management/health"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always