version: "3"
services:
 ecos:
  image: ${MONGO_TAG}
  container_name: ecos-mongodb
  hostname: ${MONGO_HOST}
  expose:
   - "27017/tcp"
  volumes:
   - "${ECOS_SRC_PATH}/mongodb/db:/data/db"
  healthcheck:
   test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always