version: "3"
services:
 ecos:
  image: ${MODEL_TAG}
  container_name: ecos-model
  hostname: ${MODEL_HOST}
  expose:
   - "8094/tcp"
  healthcheck:
   test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8094/management/health"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always