version: "3"
services:
 ecos:
  image: ${PROCESS_TAG}
  container_name: ecos-process
  hostname: ${PROCESS_HOST}
  expose:
   - "8098/tcp"
  healthcheck:
   test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8098/management/health"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always