version: "3"
services:
 ecos:
  image: ${HISTORY_TAG}
  container_name: ecos-history
  hostname: ${HISTORY_HOST}
  expose:
   - "8086/tcp"
  volumes:
   - "${ECOS_SRC_PATH}/history/source:/source"
   - "${ECOS_SRC_PATH}/history/errors:/errors"
  healthcheck:
   test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8086/management/health"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always