version: "3"
services:
 ecos:
  image: ${UISERV_TAG}
  container_name: ecos-uiserv
  hostname: ${UISERV_HOST}
  expose:
   - "8081/tcp"
  healthcheck:
   test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8081/management/health"]
   interval: 20s
   timeout: 20s
   retries: 36
  stop_grace_period: 1m
  restart: always